import 'dotenv/config';
import pg from 'pg';
const c = new pg.Client({ connectionString: process.env.DATABASE_URL, keepAlive: true });
await c.connect();
const q = async (s: string) => (await c.query(s)).rows[0].n;
console.log('tabs total                :', await q('SELECT count(*)::int n FROM tabs'));
console.log('tabs w/o membership (0)   :', await q('SELECT count(*)::int n FROM tabs t WHERE NOT EXISTS (SELECT 1 FROM board_members m WHERE m.tab_id=t.id)'));
console.log('tabs w/o admin (0)        :', await q("SELECT count(*)::int n FROM tabs t WHERE NOT EXISTS (SELECT 1 FROM board_members m WHERE m.tab_id=t.id AND m.role='admin')"));
console.log('tabs.created_by NULL (0)  :', await q('SELECT count(*)::int n FROM tabs WHERE created_by IS NULL'));
console.log('tasks.created_by NULL (0) :', await q('SELECT count(*)::int n FROM tasks WHERE created_by IS NULL'));
console.log('view-state divergence (0) :', await q('SELECT count(*)::int n FROM board_members m JOIN tabs t ON t.id=m.tab_id AND t.user_id=m.user_id WHERE m.starred IS DISTINCT FROM t.starred OR m.position IS DISTINCT FROM t.position OR m.category_id IS DISTINCT FROM t.project_id'));
await c.end();
